/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package TOT;
/**
 *
 * @author sanand
 */
public class uf12_06 extends javax.swing.JFrame {

    /**
     * Creates new form uf12_06
     * id : dado random
     */
    public uf12_06() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dado6jButton = new javax.swing.JButton();
        dado8jButton = new javax.swing.JButton();
        dado10jButton = new javax.swing.JButton();
        dado12jButton = new javax.swing.JButton();
        dado20jButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dado6jButton.setText("6");
        dado6jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado6jButtonActionPerformed(evt);
            }
        });

        dado8jButton.setText("8");
        dado8jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado8jButtonActionPerformed(evt);
            }
        });

        dado10jButton.setText("10");
        dado10jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado10jButtonActionPerformed(evt);
            }
        });

        dado12jButton.setText("12");
        dado12jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado12jButtonActionPerformed(evt);
            }
        });

        dado20jButton.setText("20");
        dado20jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado20jButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(dado6jButton)
                        .addGap(109, 109, 109)
                        .addComponent(dado8jButton)
                        .addGap(144, 144, 144)
                        .addComponent(dado10jButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(dado12jButton)
                        .addGap(135, 135, 135)
                        .addComponent(dado20jButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dado6jButton)
                    .addComponent(dado8jButton)
                    .addComponent(dado10jButton))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dado12jButton)
                    .addComponent(dado20jButton))
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dado6jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado6jButtonActionPerformed
        // TODO add your handling code here:
        // important deuria de aver fet una funció
        int min = 1;
        int max = 6;
        int random = (int) (Math.random() * (max - min + 1) + min);
        jLabel2.setText(random+"");
        
    }//GEN-LAST:event_dado6jButtonActionPerformed

    private void dado8jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado8jButtonActionPerformed
        // TODO add your handling code here:
        int min = 1;
        int max = 8;
        int random = (int) (Math.random() * (max - min + 1) + min);
        jLabel2.setText(random+"");
    }//GEN-LAST:event_dado8jButtonActionPerformed

    private void dado10jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado10jButtonActionPerformed
        // TODO add your handling code here:
        int min = 1;
        int max = 10;
        int random = (int) (Math.random() * (max - min + 1) + min);
        jLabel2.setText(random+"");
    }//GEN-LAST:event_dado10jButtonActionPerformed

    private void dado12jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado12jButtonActionPerformed
        // TODO add your handling code here:
        int min = 1;
        int max = 12;
        int random = (int) (Math.random() * (max - min + 1) + min);
        jLabel2.setText(random+"");
    }//GEN-LAST:event_dado12jButtonActionPerformed

    private void dado20jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado20jButtonActionPerformed
        // TODO add your handling code here:
        int min = 1;
        int max = 20;
        int random = (int) (Math.random() * (max - min + 1) + min);
        jLabel2.setText(random+"");
    }//GEN-LAST:event_dado20jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uf12_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uf12_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uf12_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uf12_06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uf12_06().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dado10jButton;
    private javax.swing.JButton dado12jButton;
    private javax.swing.JButton dado20jButton;
    private javax.swing.JButton dado6jButton;
    private javax.swing.JButton dado8jButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
