/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uf12_Burger;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.plaf.basic.BasicBorders;

/**
 *
 * @author Andreuet
 */
public class UF12_Burger extends javax.swing.JFrame {

    /**
     * Creates new form UF12_08
     */
    public UF12_Burger() {
        initComponents();
        qchupjSpinner.setVisible(false);
        bbcoajSpinner.setVisible(false);
        mastassajSpinner.setVisible(false);
        thaijSpinner.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pajLabel = new javax.swing.JLabel();
        pajComboBox = new javax.swing.JComboBox<>();
        hamburguesajLabel = new javax.swing.JLabel();
        hamburguesajComboBox = new javax.swing.JComboBox<>();
        creillesjLabel = new javax.swing.JLabel();
        creillesjComboBox = new javax.swing.JComboBox<>();
        begudajLabel = new javax.swing.JLabel();
        begudajComboBox = new javax.swing.JComboBox<>();
        entregajLabel = new javax.swing.JLabel();
        entregajComboBox = new javax.swing.JComboBox<>();
        preujButton = new javax.swing.JButton();
        preujLabel = new javax.swing.JLabel();
        extrajLabel1 = new javax.swing.JLabel();
        extrajLabel2 = new javax.swing.JLabel();
        extrajLabel3 = new javax.swing.JLabel();
        extrajLabel4 = new javax.swing.JLabel();
        HMBjSpinner = new javax.swing.JSpinner();
        chessjSpinner = new javax.swing.JSpinner();
        pttjSpinner = new javax.swing.JSpinner();
        qchuojRadioButton = new javax.swing.JRadioButton();
        bbcoajRadioButton = new javax.swing.JRadioButton();
        mostassjRadioButton = new javax.swing.JRadioButton();
        thaiujRadioButton = new javax.swing.JRadioButton();
        qchupjSpinner = new javax.swing.JSpinner();
        bbcoajSpinner = new javax.swing.JSpinner();
        mastassajSpinner = new javax.swing.JSpinner();
        thaijSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pajLabel.setText("Tipo de pa");

        pajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Normal", "Integral", "Sègol" }));
        pajComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pajComboBoxActionPerformed(evt);
            }
        });

        hamburguesajLabel.setText("Haburguesa");

        hamburguesajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Pollastre", "Porc", "Vedella (+1€)", "Vegana (+1€)" }));

        creillesjLabel.setText("Creïlles");

        creillesjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Fregides", "Grill", "Casolanes (+1€)" }));
        creillesjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creillesjComboBoxActionPerformed(evt);
            }
        });

        begudajLabel.setText("Beguda");

        begudajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Refresc de cola", "Refresc de taronja", "Refresc de llima", "Aigua ", "Cervesa" }));
        begudajComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                begudajComboBoxActionPerformed(evt);
            }
        });

        entregajLabel.setText("Tipo de entrega");

        entregajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Repartiment a domicili ", "Recollida en el local (-20%)" }));
        entregajComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregajComboBoxActionPerformed(evt);
            }
        });

        preujButton.setText("Preu Total");
        preujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preujButtonActionPerformed(evt);
            }
        });

        preujLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        extrajLabel1.setText("amburguesa doble (+2€)");

        extrajLabel2.setText("Extra de formatge (+0,50)");

        extrajLabel3.setText("Extra de creïlles (+1€)");

        extrajLabel4.setText("Salses (+0,50 cadauna)");

        HMBjSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        chessjSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        pttjSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        qchuojRadioButton.setText("quètxup");
        qchuojRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qchuojRadioButtonActionPerformed(evt);
            }
        });

        bbcoajRadioButton.setText("barbacoa");
        bbcoajRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbcoajRadioButtonActionPerformed(evt);
            }
        });

        mostassjRadioButton.setText("mostassa");
        mostassjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostassjRadioButtonActionPerformed(evt);
            }
        });

        thaiujRadioButton.setText("thai");
        thaiujRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thaiujRadioButtonActionPerformed(evt);
            }
        });

        qchupjSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        bbcoajSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        mastassajSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        thaijSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entregajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(begudajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(creillesjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hamburguesajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creillesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hamburguesajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(begudajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entregajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(extrajLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pttjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(extrajLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chessjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(extrajLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(HMBjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(extrajLabel4)
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(bbcoajRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(bbcoajSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(qchuojRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(qchupjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(mostassjRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(mastassajSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(thaiujRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(thaijSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(preujLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(preujButton)))
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {begudajComboBox, creillesjComboBox, entregajComboBox, hamburguesajComboBox, pajComboBox});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bbcoajRadioButton, mostassjRadioButton, qchuojRadioButton, thaiujRadioButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hamburguesajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(hamburguesajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(pajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creillesjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(creillesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(begudajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(begudajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entregajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(entregajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extrajLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HMBjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extrajLabel2)
                    .addComponent(chessjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extrajLabel3)
                    .addComponent(pttjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(extrajLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qchuojRadioButton)
                            .addComponent(qchupjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbcoajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbcoajSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostassjRadioButton)
                    .addComponent(mastassajSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thaiujRadioButton)
                    .addComponent(thaijSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(preujButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preujLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bbcoajRadioButton, mostassjRadioButton, qchuojRadioButton, thaiujRadioButton});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {HMBjSpinner, chessjSpinner, extrajLabel1, extrajLabel2, extrajLabel3, extrajLabel4, pttjSpinner});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pajComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pajComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pajComboBoxActionPerformed

    private void creillesjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creillesjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creillesjComboBoxActionPerformed

    private void begudajComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_begudajComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_begudajComboBoxActionPerformed

    private void entregajComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregajComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entregajComboBoxActionPerformed

    private void bbcoajRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbcoajRadioButtonActionPerformed
        // TODO add your handling code here:
        if (bbcoajRadioButton.isSelected()) {
            bbcoajSpinner.setVisible(true);
        } else
            bbcoajSpinner.setVisible(false);
    }//GEN-LAST:event_bbcoajRadioButtonActionPerformed

    private void qchuojRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qchuojRadioButtonActionPerformed
        // TODO add your handling code here:
        if (qchuojRadioButton.isSelected()) {
            qchupjSpinner.setVisible(true);
        } else
            qchupjSpinner.setVisible(false);
    }//GEN-LAST:event_qchuojRadioButtonActionPerformed

    private void mostassjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostassjRadioButtonActionPerformed
        // TODO add your handling code here:
        if (mostassjRadioButton.isSelected()) {
            mastassajSpinner.setVisible(true);
        } else
            mastassajSpinner.setVisible(false);
    }//GEN-LAST:event_mostassjRadioButtonActionPerformed

    private void thaiujRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thaiujRadioButtonActionPerformed
        // TODO add your handling code here:
        if (thaiujRadioButton.isSelected()) {
            thaijSpinner.setVisible(true);
        } else
            thaijSpinner.setVisible(false);
    }//GEN-LAST:event_thaiujRadioButtonActionPerformed

    public static int sumarnum(String sel) {
        if (sel.contains("+1")) {
                return 1;
            }
        return 0;
    }
    private void preujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preujButtonActionPerformed
        // TODO add your handling code here:
        preujLabel.setText("");
        double preu = 8;
        if (hamburguesajComboBox.getSelectedIndex() == 0 || begudajComboBox.getSelectedIndex() == 0 || creillesjComboBox.getSelectedIndex() == 0 || entregajComboBox.getSelectedIndex() == 0) {
            preujLabel.setText("Has de seleccionar tots els camps obligatoris");

        } else {
            preu += sumarnum((String) hamburguesajComboBox.getSelectedItem());
            preu += sumarnum((String) creillesjComboBox.getSelectedItem());
            
            preu += (int)HMBjSpinner.getValue() * 2
                    + ((int) chessjSpinner.getValue()
                    + (int) qchupjSpinner.getValue()
                    + (int) bbcoajSpinner.getValue()
                    + (int) mastassajSpinner.getValue()
                    + (int) thaijSpinner.getValue()) * 0.5
                    + (int) pttjSpinner.getValue();
            
            if (entregajComboBox.getSelectedIndex() == 2) {
                preu *= 0.8;
            }
            
            
            String tot = "<html>Preu de venta al public : " + String.format("%.2f", preu*1.21)
                    + "<br>Preu de venta sense IVA : " + String.format("%.2f", preu) + "</html>";
            preujLabel.setText(tot);
           

        }
    }//GEN-LAST:event_preujButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UF12_Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UF12_Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UF12_Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UF12_Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UF12_Burger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner HMBjSpinner;
    private javax.swing.JRadioButton bbcoajRadioButton;
    private javax.swing.JSpinner bbcoajSpinner;
    private javax.swing.JComboBox<String> begudajComboBox;
    private javax.swing.JLabel begudajLabel;
    private javax.swing.JSpinner chessjSpinner;
    private javax.swing.JComboBox<String> creillesjComboBox;
    private javax.swing.JLabel creillesjLabel;
    private javax.swing.JComboBox<String> entregajComboBox;
    private javax.swing.JLabel entregajLabel;
    private javax.swing.JLabel extrajLabel1;
    private javax.swing.JLabel extrajLabel2;
    private javax.swing.JLabel extrajLabel3;
    private javax.swing.JLabel extrajLabel4;
    private javax.swing.JComboBox<String> hamburguesajComboBox;
    private javax.swing.JLabel hamburguesajLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner mastassajSpinner;
    private javax.swing.JRadioButton mostassjRadioButton;
    private javax.swing.JComboBox<String> pajComboBox;
    private javax.swing.JLabel pajLabel;
    private javax.swing.JButton preujButton;
    private javax.swing.JLabel preujLabel;
    private javax.swing.JSpinner pttjSpinner;
    private javax.swing.JRadioButton qchuojRadioButton;
    private javax.swing.JSpinner qchupjSpinner;
    private javax.swing.JSpinner thaijSpinner;
    private javax.swing.JRadioButton thaiujRadioButton;
    // End of variables declaration//GEN-END:variables
}
